services:
  couchdb:
    image: couchdb:3.5
    environment:
      COUCHDB_USERNAME: admin
      COUCHDB_PASSWORD: password
      IOT_DBNAME: iot
      WO_DBNAME: workorder
      VIBRATION_DBNAME: vibration
    ports:
      - "5984:5984"
    volumes:
      - couchdb-data:/opt/couchdb/data
      - ./couchdb_setup.sh:/opt/couchdb/etc/couchdb_setup.sh
      - ./:/couchdb
    command: ["sh", "/opt/couchdb/etc/couchdb_setup.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  couchdb-data:
